// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-variants/Gold.tsx": () => import("../components/mockups/color-variants/Gold.tsx"),
  "./components/mockups/color-variants/NeonGreen.tsx": () => import("../components/mockups/color-variants/NeonGreen.tsx"),
  "./components/mockups/color-variants/PinkCyan.tsx": () => import("../components/mockups/color-variants/PinkCyan.tsx"),
  "./components/mockups/color-variants/Purple.tsx": () => import("../components/mockups/color-variants/Purple.tsx")
};
